### PR TITLE
resolves #3 add essential branding and footer copy

### LINKED ISSUE #3: Add essential Asciidoctor branding
Add the essential Asciidoctor branding elements to the UI. This includes the logo in the navbar, colors, favicon, and project information in the footer. Since the focus right now is on the content, we don't have time to dedicate to designing a custom UI. But we should at least get the essentials in there so that it feels like an Asciidoctor property.

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by graphitefriction** [comment]
@mojavelinux The footer has some positioning issues.

image

And I'd like the size of "Asciidoctor Docs" in the navbar to be just a bit bigger than the navigation links.

**Comment by mojavelinux** [comment]
It looks like we're having problems with the intrinsic width in the SVG. I'll remove that and it should resolve this issue. I'll also check the positioning issue. The SVG should be centered.

**Comment by mojavelinux** [comment]
Fixed. Just needed to set the height and fix the flex alignment.

**Comment by Mogztter** [comment]
### Responsive

I think we should use responsive column to switch to one column for mobile and tablet (otherwise the content is overlapping):

**tablet**
deploy-preview-4--asciidoctor-docs-ui netlify com_ 1

**mobile**
deploy-preview-4--asciidoctor-docs-ui netlify com_ 2


### Font family

Should we use Comfortaa for "Asciidoctor":

deploy-preview-4--asciidoctor-docs-ui netlify com_ 4

**Comment by mojavelinux** [comment]
You're right, we should make the footer responsive. I was trying to keep the customization to a minimum, but this affects the mobile experience quite dramatically, so it's worth doing.

I agree with you about the Comfortaa text. I was going to wait until the logo with type was ready, but it's easy enough to load the font that we should probably just do it to keep the branding consistent.

**Comment by mojavelinux** [comment]
Updated. It should be good to go now.

Keep in mind, we're just trying to do the bare minimum here until we have time to design a proper theme.

**Comment by Mogztter** [comment]
Looking good, well done!

screenshot_20181110-190921

**Comment by mojavelinux** [comment]
For some reason, the Comfortaa font isn't loading in the preview. I think it might be a caching problem.

**Comment by mojavelinux** [comment]
I had forgotten to add it to the master file. All fixed.

**Pull request merged**
